- name: Install nginx on Ubuntu
  hosts: localhost
  tasks:
  - name: Update Cache
    apt:
      update_cache: yes
    become: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: present
    become: yes
 
  - name: Install PHP
    apt:
      name: php
      state: present
    become: yes

  - name: Install required Packages
    apt:
      name: "{{item}}"
      state: present
    become: yes
    with_items: 
      - php
      - mysql-client
      - mysql-server
      - php-mysql
      - php-xml
      - snmp
      - snmpd
      - rrdtool

  - name: Install Cacti
    apt:
      name: cacti
      state: present
    become: yes
       
       
